[package]
name = "quick-protobuf"
description = "A pure Rust protobuf (de)serializer. Quick."
version = "0.8.1"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
keywords = ["protobuf", "parser"]
license = "MIT"
readme = "README.md" 
documentation = "https://docs.rs/quick-protobuf"
repository = "https://github.com/tafia/quick-protobuf"
edition = "2018"
rust-version = "1.62.1"

[dependencies]
byteorder = { version = "1.5.0", default-features = false }

[dev-dependencies]
lazy_static = "1.5.0"
trybuild = "1.0.116"
quickcheck = "1.1.0"

[features]
default = ["std"]
std = ["byteorder/std"]
