// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `perftest_data.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:perftest_data.Test1)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Test1 {
    // message fields
    // @@protoc_insertion_point(field:perftest_data.Test1.value)
    pub value: ::std::option::Option<i32>,
    // special fields
    // @@protoc_insertion_point(special_field:perftest_data.Test1.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Test1 {
    fn default() -> &'a Test1 {
        <Test1 as ::protobuf::Message>::default_instance()
    }
}

impl Test1 {
    pub fn new() -> Test1 {
        ::std::default::Default::default()
    }

    // optional int32 value = 1;

    pub fn value(&self) -> i32 {
        self.value.unwrap_or(0)
    }

    pub fn clear_value(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_value(&self) -> bool {
        self.value.is_some()
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: i32) {
        self.value = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "value",
            |m: &Test1| { &m.value },
            |m: &mut Test1| { &mut m.value },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Test1>(
            "Test1",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Test1 {
    const NAME: &'static str = "Test1";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.value = ::std::option::Option::Some(is.read_int32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.value {
            my_size += ::protobuf::rt::int32_size(1, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.value {
            os.write_int32(1, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Test1 {
        Test1::new()
    }

    fn clear(&mut self) {
        self.value = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Test1 {
        static instance: Test1 = Test1 {
            value: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Test1 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Test1").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Test1 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Test1 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:perftest_data.TestRepeatedBool)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TestRepeatedBool {
    // message fields
    // @@protoc_insertion_point(field:perftest_data.TestRepeatedBool.values)
    pub values: ::std::vec::Vec<bool>,
    // special fields
    // @@protoc_insertion_point(special_field:perftest_data.TestRepeatedBool.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TestRepeatedBool {
    fn default() -> &'a TestRepeatedBool {
        <TestRepeatedBool as ::protobuf::Message>::default_instance()
    }
}

impl TestRepeatedBool {
    pub fn new() -> TestRepeatedBool {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "values",
            |m: &TestRepeatedBool| { &m.values },
            |m: &mut TestRepeatedBool| { &mut m.values },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TestRepeatedBool>(
            "TestRepeatedBool",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TestRepeatedBool {
    const NAME: &'static str = "TestRepeatedBool";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    is.read_repeated_packed_bool_into(&mut self.values)?;
                },
                8 => {
                    self.values.push(is.read_bool()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += 2 * self.values.len() as u64;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.values {
            os.write_bool(1, *v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TestRepeatedBool {
        TestRepeatedBool::new()
    }

    fn clear(&mut self) {
        self.values.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TestRepeatedBool {
        static instance: TestRepeatedBool = TestRepeatedBool {
            values: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TestRepeatedBool {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TestRepeatedBool").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TestRepeatedBool {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestRepeatedBool {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:perftest_data.TestRepeatedPackedInt32)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TestRepeatedPackedInt32 {
    // message fields
    // @@protoc_insertion_point(field:perftest_data.TestRepeatedPackedInt32.values)
    pub values: ::std::vec::Vec<i32>,
    // special fields
    // @@protoc_insertion_point(special_field:perftest_data.TestRepeatedPackedInt32.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TestRepeatedPackedInt32 {
    fn default() -> &'a TestRepeatedPackedInt32 {
        <TestRepeatedPackedInt32 as ::protobuf::Message>::default_instance()
    }
}

impl TestRepeatedPackedInt32 {
    pub fn new() -> TestRepeatedPackedInt32 {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "values",
            |m: &TestRepeatedPackedInt32| { &m.values },
            |m: &mut TestRepeatedPackedInt32| { &mut m.values },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TestRepeatedPackedInt32>(
            "TestRepeatedPackedInt32",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TestRepeatedPackedInt32 {
    const NAME: &'static str = "TestRepeatedPackedInt32";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    is.read_repeated_packed_int32_into(&mut self.values)?;
                },
                8 => {
                    self.values.push(is.read_int32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::vec_packed_int32_size(1, &self.values);
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_repeated_packed_int32(1, &self.values)?;
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TestRepeatedPackedInt32 {
        TestRepeatedPackedInt32::new()
    }

    fn clear(&mut self) {
        self.values.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TestRepeatedPackedInt32 {
        static instance: TestRepeatedPackedInt32 = TestRepeatedPackedInt32 {
            values: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TestRepeatedPackedInt32 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TestRepeatedPackedInt32").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TestRepeatedPackedInt32 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestRepeatedPackedInt32 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:perftest_data.TestRepeatedMessages)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TestRepeatedMessages {
    // message fields
    // @@protoc_insertion_point(field:perftest_data.TestRepeatedMessages.messages1)
    pub messages1: ::std::vec::Vec<TestRepeatedMessages>,
    // @@protoc_insertion_point(field:perftest_data.TestRepeatedMessages.messages2)
    pub messages2: ::std::vec::Vec<TestRepeatedMessages>,
    // @@protoc_insertion_point(field:perftest_data.TestRepeatedMessages.messages3)
    pub messages3: ::std::vec::Vec<TestRepeatedMessages>,
    // special fields
    // @@protoc_insertion_point(special_field:perftest_data.TestRepeatedMessages.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TestRepeatedMessages {
    fn default() -> &'a TestRepeatedMessages {
        <TestRepeatedMessages as ::protobuf::Message>::default_instance()
    }
}

impl TestRepeatedMessages {
    pub fn new() -> TestRepeatedMessages {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "messages1",
            |m: &TestRepeatedMessages| { &m.messages1 },
            |m: &mut TestRepeatedMessages| { &mut m.messages1 },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "messages2",
            |m: &TestRepeatedMessages| { &m.messages2 },
            |m: &mut TestRepeatedMessages| { &mut m.messages2 },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "messages3",
            |m: &TestRepeatedMessages| { &m.messages3 },
            |m: &mut TestRepeatedMessages| { &mut m.messages3 },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TestRepeatedMessages>(
            "TestRepeatedMessages",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TestRepeatedMessages {
    const NAME: &'static str = "TestRepeatedMessages";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.messages1.push(is.read_message()?);
                },
                18 => {
                    self.messages2.push(is.read_message()?);
                },
                26 => {
                    self.messages3.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.messages1 {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.messages2 {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.messages3 {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.messages1 {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        for v in &self.messages2 {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        for v in &self.messages3 {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TestRepeatedMessages {
        TestRepeatedMessages::new()
    }

    fn clear(&mut self) {
        self.messages1.clear();
        self.messages2.clear();
        self.messages3.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TestRepeatedMessages {
        static instance: TestRepeatedMessages = TestRepeatedMessages {
            messages1: ::std::vec::Vec::new(),
            messages2: ::std::vec::Vec::new(),
            messages3: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TestRepeatedMessages {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TestRepeatedMessages").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TestRepeatedMessages {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestRepeatedMessages {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:perftest_data.TestOptionalMessages)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TestOptionalMessages {
    // message fields
    // @@protoc_insertion_point(field:perftest_data.TestOptionalMessages.message1)
    pub message1: ::protobuf::MessageField<TestOptionalMessages>,
    // @@protoc_insertion_point(field:perftest_data.TestOptionalMessages.message2)
    pub message2: ::protobuf::MessageField<TestOptionalMessages>,
    // @@protoc_insertion_point(field:perftest_data.TestOptionalMessages.message3)
    pub message3: ::protobuf::MessageField<TestOptionalMessages>,
    // special fields
    // @@protoc_insertion_point(special_field:perftest_data.TestOptionalMessages.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TestOptionalMessages {
    fn default() -> &'a TestOptionalMessages {
        <TestOptionalMessages as ::protobuf::Message>::default_instance()
    }
}

impl TestOptionalMessages {
    pub fn new() -> TestOptionalMessages {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, TestOptionalMessages>(
            "message1",
            |m: &TestOptionalMessages| { &m.message1 },
            |m: &mut TestOptionalMessages| { &mut m.message1 },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, TestOptionalMessages>(
            "message2",
            |m: &TestOptionalMessages| { &m.message2 },
            |m: &mut TestOptionalMessages| { &mut m.message2 },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, TestOptionalMessages>(
            "message3",
            |m: &TestOptionalMessages| { &m.message3 },
            |m: &mut TestOptionalMessages| { &mut m.message3 },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TestOptionalMessages>(
            "TestOptionalMessages",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TestOptionalMessages {
    const NAME: &'static str = "TestOptionalMessages";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.message1)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.message2)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.message3)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.message1.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.message2.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.message3.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.message1.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.message2.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.message3.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TestOptionalMessages {
        TestOptionalMessages::new()
    }

    fn clear(&mut self) {
        self.message1.clear();
        self.message2.clear();
        self.message3.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TestOptionalMessages {
        static instance: TestOptionalMessages = TestOptionalMessages {
            message1: ::protobuf::MessageField::none(),
            message2: ::protobuf::MessageField::none(),
            message3: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TestOptionalMessages {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TestOptionalMessages").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TestOptionalMessages {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestOptionalMessages {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:perftest_data.TestStrings)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TestStrings {
    // message fields
    // @@protoc_insertion_point(field:perftest_data.TestStrings.s1)
    pub s1: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:perftest_data.TestStrings.s2)
    pub s2: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:perftest_data.TestStrings.s3)
    pub s3: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:perftest_data.TestStrings.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TestStrings {
    fn default() -> &'a TestStrings {
        <TestStrings as ::protobuf::Message>::default_instance()
    }
}

impl TestStrings {
    pub fn new() -> TestStrings {
        ::std::default::Default::default()
    }

    // optional string s1 = 1;

    pub fn s1(&self) -> &str {
        match self.s1.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_s1(&mut self) {
        self.s1 = ::std::option::Option::None;
    }

    pub fn has_s1(&self) -> bool {
        self.s1.is_some()
    }

    // Param is passed by value, moved
    pub fn set_s1(&mut self, v: ::std::string::String) {
        self.s1 = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_s1(&mut self) -> &mut ::std::string::String {
        if self.s1.is_none() {
            self.s1 = ::std::option::Option::Some(::std::string::String::new());
        }
        self.s1.as_mut().unwrap()
    }

    // Take field
    pub fn take_s1(&mut self) -> ::std::string::String {
        self.s1.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string s2 = 2;

    pub fn s2(&self) -> &str {
        match self.s2.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_s2(&mut self) {
        self.s2 = ::std::option::Option::None;
    }

    pub fn has_s2(&self) -> bool {
        self.s2.is_some()
    }

    // Param is passed by value, moved
    pub fn set_s2(&mut self, v: ::std::string::String) {
        self.s2 = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_s2(&mut self) -> &mut ::std::string::String {
        if self.s2.is_none() {
            self.s2 = ::std::option::Option::Some(::std::string::String::new());
        }
        self.s2.as_mut().unwrap()
    }

    // Take field
    pub fn take_s2(&mut self) -> ::std::string::String {
        self.s2.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string s3 = 3;

    pub fn s3(&self) -> &str {
        match self.s3.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_s3(&mut self) {
        self.s3 = ::std::option::Option::None;
    }

    pub fn has_s3(&self) -> bool {
        self.s3.is_some()
    }

    // Param is passed by value, moved
    pub fn set_s3(&mut self, v: ::std::string::String) {
        self.s3 = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_s3(&mut self) -> &mut ::std::string::String {
        if self.s3.is_none() {
            self.s3 = ::std::option::Option::Some(::std::string::String::new());
        }
        self.s3.as_mut().unwrap()
    }

    // Take field
    pub fn take_s3(&mut self) -> ::std::string::String {
        self.s3.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "s1",
            |m: &TestStrings| { &m.s1 },
            |m: &mut TestStrings| { &mut m.s1 },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "s2",
            |m: &TestStrings| { &m.s2 },
            |m: &mut TestStrings| { &mut m.s2 },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "s3",
            |m: &TestStrings| { &m.s3 },
            |m: &mut TestStrings| { &mut m.s3 },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TestStrings>(
            "TestStrings",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TestStrings {
    const NAME: &'static str = "TestStrings";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.s1 = ::std::option::Option::Some(is.read_string()?);
                },
                18 => {
                    self.s2 = ::std::option::Option::Some(is.read_string()?);
                },
                26 => {
                    self.s3 = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.s1.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(v) = self.s2.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(v) = self.s3.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.s1.as_ref() {
            os.write_string(1, v)?;
        }
        if let Some(v) = self.s2.as_ref() {
            os.write_string(2, v)?;
        }
        if let Some(v) = self.s3.as_ref() {
            os.write_string(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TestStrings {
        TestStrings::new()
    }

    fn clear(&mut self) {
        self.s1 = ::std::option::Option::None;
        self.s2 = ::std::option::Option::None;
        self.s3 = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TestStrings {
        static instance: TestStrings = TestStrings {
            s1: ::std::option::Option::None,
            s2: ::std::option::Option::None,
            s3: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TestStrings {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TestStrings").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TestStrings {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestStrings {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:perftest_data.TestBytes)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TestBytes {
    // message fields
    // @@protoc_insertion_point(field:perftest_data.TestBytes.b1)
    pub b1: ::std::option::Option<::std::vec::Vec<u8>>,
    // special fields
    // @@protoc_insertion_point(special_field:perftest_data.TestBytes.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TestBytes {
    fn default() -> &'a TestBytes {
        <TestBytes as ::protobuf::Message>::default_instance()
    }
}

impl TestBytes {
    pub fn new() -> TestBytes {
        ::std::default::Default::default()
    }

    // optional bytes b1 = 1;

    pub fn b1(&self) -> &[u8] {
        match self.b1.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_b1(&mut self) {
        self.b1 = ::std::option::Option::None;
    }

    pub fn has_b1(&self) -> bool {
        self.b1.is_some()
    }

    // Param is passed by value, moved
    pub fn set_b1(&mut self, v: ::std::vec::Vec<u8>) {
        self.b1 = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_b1(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.b1.is_none() {
            self.b1 = ::std::option::Option::Some(::std::vec::Vec::new());
        }
        self.b1.as_mut().unwrap()
    }

    // Take field
    pub fn take_b1(&mut self) -> ::std::vec::Vec<u8> {
        self.b1.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "b1",
            |m: &TestBytes| { &m.b1 },
            |m: &mut TestBytes| { &mut m.b1 },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TestBytes>(
            "TestBytes",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TestBytes {
    const NAME: &'static str = "TestBytes";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.b1 = ::std::option::Option::Some(is.read_bytes()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.b1.as_ref() {
            my_size += ::protobuf::rt::bytes_size(1, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.b1.as_ref() {
            os.write_bytes(1, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TestBytes {
        TestBytes::new()
    }

    fn clear(&mut self) {
        self.b1 = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TestBytes {
        static instance: TestBytes = TestBytes {
            b1: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TestBytes {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TestBytes").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TestBytes {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestBytes {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:perftest_data.PerftestData)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PerftestData {
    // message fields
    // @@protoc_insertion_point(field:perftest_data.PerftestData.test1)
    pub test1: ::std::vec::Vec<Test1>,
    // @@protoc_insertion_point(field:perftest_data.PerftestData.test_repeated_bool)
    pub test_repeated_bool: ::std::vec::Vec<TestRepeatedBool>,
    // @@protoc_insertion_point(field:perftest_data.PerftestData.test_repeated_messages)
    pub test_repeated_messages: ::std::vec::Vec<TestRepeatedMessages>,
    // @@protoc_insertion_point(field:perftest_data.PerftestData.test_optional_messages)
    pub test_optional_messages: ::std::vec::Vec<TestOptionalMessages>,
    // @@protoc_insertion_point(field:perftest_data.PerftestData.test_strings)
    pub test_strings: ::std::vec::Vec<TestStrings>,
    // @@protoc_insertion_point(field:perftest_data.PerftestData.test_repeated_packed_int32)
    pub test_repeated_packed_int32: ::std::vec::Vec<TestRepeatedPackedInt32>,
    // @@protoc_insertion_point(field:perftest_data.PerftestData.test_small_bytearrays)
    pub test_small_bytearrays: ::std::vec::Vec<TestBytes>,
    // @@protoc_insertion_point(field:perftest_data.PerftestData.test_large_bytearrays)
    pub test_large_bytearrays: ::std::vec::Vec<TestBytes>,
    // special fields
    // @@protoc_insertion_point(special_field:perftest_data.PerftestData.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PerftestData {
    fn default() -> &'a PerftestData {
        <PerftestData as ::protobuf::Message>::default_instance()
    }
}

impl PerftestData {
    pub fn new() -> PerftestData {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "test1",
            |m: &PerftestData| { &m.test1 },
            |m: &mut PerftestData| { &mut m.test1 },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "test_repeated_bool",
            |m: &PerftestData| { &m.test_repeated_bool },
            |m: &mut PerftestData| { &mut m.test_repeated_bool },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "test_repeated_messages",
            |m: &PerftestData| { &m.test_repeated_messages },
            |m: &mut PerftestData| { &mut m.test_repeated_messages },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "test_optional_messages",
            |m: &PerftestData| { &m.test_optional_messages },
            |m: &mut PerftestData| { &mut m.test_optional_messages },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "test_strings",
            |m: &PerftestData| { &m.test_strings },
            |m: &mut PerftestData| { &mut m.test_strings },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "test_repeated_packed_int32",
            |m: &PerftestData| { &m.test_repeated_packed_int32 },
            |m: &mut PerftestData| { &mut m.test_repeated_packed_int32 },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "test_small_bytearrays",
            |m: &PerftestData| { &m.test_small_bytearrays },
            |m: &mut PerftestData| { &mut m.test_small_bytearrays },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "test_large_bytearrays",
            |m: &PerftestData| { &m.test_large_bytearrays },
            |m: &mut PerftestData| { &mut m.test_large_bytearrays },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PerftestData>(
            "PerftestData",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PerftestData {
    const NAME: &'static str = "PerftestData";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.test1.push(is.read_message()?);
                },
                18 => {
                    self.test_repeated_bool.push(is.read_message()?);
                },
                26 => {
                    self.test_repeated_messages.push(is.read_message()?);
                },
                34 => {
                    self.test_optional_messages.push(is.read_message()?);
                },
                42 => {
                    self.test_strings.push(is.read_message()?);
                },
                50 => {
                    self.test_repeated_packed_int32.push(is.read_message()?);
                },
                58 => {
                    self.test_small_bytearrays.push(is.read_message()?);
                },
                66 => {
                    self.test_large_bytearrays.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.test1 {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.test_repeated_bool {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.test_repeated_messages {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.test_optional_messages {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.test_strings {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.test_repeated_packed_int32 {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.test_small_bytearrays {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.test_large_bytearrays {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.test1 {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        for v in &self.test_repeated_bool {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        for v in &self.test_repeated_messages {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        for v in &self.test_optional_messages {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        for v in &self.test_strings {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        };
        for v in &self.test_repeated_packed_int32 {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        };
        for v in &self.test_small_bytearrays {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        };
        for v in &self.test_large_bytearrays {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PerftestData {
        PerftestData::new()
    }

    fn clear(&mut self) {
        self.test1.clear();
        self.test_repeated_bool.clear();
        self.test_repeated_messages.clear();
        self.test_optional_messages.clear();
        self.test_strings.clear();
        self.test_repeated_packed_int32.clear();
        self.test_small_bytearrays.clear();
        self.test_large_bytearrays.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PerftestData {
        static instance: PerftestData = PerftestData {
            test1: ::std::vec::Vec::new(),
            test_repeated_bool: ::std::vec::Vec::new(),
            test_repeated_messages: ::std::vec::Vec::new(),
            test_optional_messages: ::std::vec::Vec::new(),
            test_strings: ::std::vec::Vec::new(),
            test_repeated_packed_int32: ::std::vec::Vec::new(),
            test_small_bytearrays: ::std::vec::Vec::new(),
            test_large_bytearrays: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PerftestData {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PerftestData").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PerftestData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PerftestData {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13perftest_data.proto\x12\rperftest_data\"\x1d\n\x05Test1\x12\x14\n\
    \x05value\x18\x01\x20\x01(\x05R\x05value\"*\n\x10TestRepeatedBool\x12\
    \x16\n\x06values\x18\x01\x20\x03(\x08R\x06values\"5\n\x17TestRepeatedPac\
    kedInt32\x12\x1a\n\x06values\x18\x01\x20\x03(\x05R\x06valuesB\x02\x10\
    \x01\"\xdf\x01\n\x14TestRepeatedMessages\x12A\n\tmessages1\x18\x01\x20\
    \x03(\x0b2#.perftest_data.TestRepeatedMessagesR\tmessages1\x12A\n\tmessa\
    ges2\x18\x02\x20\x03(\x0b2#.perftest_data.TestRepeatedMessagesR\tmessage\
    s2\x12A\n\tmessages3\x18\x03\x20\x03(\x0b2#.perftest_data.TestRepeatedMe\
    ssagesR\tmessages3\"\xd9\x01\n\x14TestOptionalMessages\x12?\n\x08message\
    1\x18\x01\x20\x01(\x0b2#.perftest_data.TestOptionalMessagesR\x08message1\
    \x12?\n\x08message2\x18\x02\x20\x01(\x0b2#.perftest_data.TestOptionalMes\
    sagesR\x08message2\x12?\n\x08message3\x18\x03\x20\x01(\x0b2#.perftest_da\
    ta.TestOptionalMessagesR\x08message3\"=\n\x0bTestStrings\x12\x0e\n\x02s1\
    \x18\x01\x20\x01(\tR\x02s1\x12\x0e\n\x02s2\x18\x02\x20\x01(\tR\x02s2\x12\
    \x0e\n\x02s3\x18\x03\x20\x01(\tR\x02s3\"\x1b\n\tTestBytes\x12\x0e\n\x02b\
    1\x18\x01\x20\x01(\x0cR\x02b1\"\xff\x04\n\x0cPerftestData\x12*\n\x05test\
    1\x18\x01\x20\x03(\x0b2\x14.perftest_data.Test1R\x05test1\x12M\n\x12test\
    _repeated_bool\x18\x02\x20\x03(\x0b2\x1f.perftest_data.TestRepeatedBoolR\
    \x10testRepeatedBool\x12Y\n\x16test_repeated_messages\x18\x03\x20\x03(\
    \x0b2#.perftest_data.TestRepeatedMessagesR\x14testRepeatedMessages\x12Y\
    \n\x16test_optional_messages\x18\x04\x20\x03(\x0b2#.perftest_data.TestOp\
    tionalMessagesR\x14testOptionalMessages\x12=\n\x0ctest_strings\x18\x05\
    \x20\x03(\x0b2\x1a.perftest_data.TestStringsR\x0btestStrings\x12c\n\x1at\
    est_repeated_packed_int32\x18\x06\x20\x03(\x0b2&.perftest_data.TestRepea\
    tedPackedInt32R\x17testRepeatedPackedInt32\x12L\n\x15test_small_bytearra\
    ys\x18\x07\x20\x03(\x0b2\x18.perftest_data.TestBytesR\x13testSmallBytear\
    rays\x12L\n\x15test_large_bytearrays\x18\x08\x20\x03(\x0b2\x18.perftest_\
    data.TestBytesR\x13testLargeBytearrays2E\n\x0fPerftestService\x122\n\x04\
    test\x12\x14.perftest_data.Test1\x1a\x14.perftest_data.Test1b\x06proto2\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(8);
            messages.push(Test1::generated_message_descriptor_data());
            messages.push(TestRepeatedBool::generated_message_descriptor_data());
            messages.push(TestRepeatedPackedInt32::generated_message_descriptor_data());
            messages.push(TestRepeatedMessages::generated_message_descriptor_data());
            messages.push(TestOptionalMessages::generated_message_descriptor_data());
            messages.push(TestStrings::generated_message_descriptor_data());
            messages.push(TestBytes::generated_message_descriptor_data());
            messages.push(PerftestData::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
