[package]
name = "perftest"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>",
           "Johann Tuffe <tafia973@gmail.com>"]
build = "build.rs"
edition = "2021"
rust-version = "1.70"

[dependencies]
protobuf = "3"
quick-protobuf = { path = "../quick-protobuf" }
rand = "0.9"
prost = "0.13"
bytes = "1"

[build-dependencies]
protobuf-codegen = "3"
pb-rs = { path = "../pb-rs" }
prost-build = "0.13"

[features]
